apiVersion: v1
kind: Service
metadata:
  name: k8s-devops-demo-service
spec:
  selector:
    app: k8s-devops-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
